sudo: required
dist: trusty

language: python
python:
    - "3.4"

install:
    - pip install -r requirements.txt

script:
    - coverage run  --source seasonal_jpop_scraper setup.py test
    - coverage report -m
