sudo: required
dist: trusty

language: python
python:
    - "3.4"

install:
    - pip install -r requirements.txt

script:
    - coverage run anime.py
    - coverage report -m
    - coverage run scraper.py
    - coverage report -m
