sudo: required
dist: trusty

language: python
python:
    - "3.4"

install:
    - pip install -r requirements.txt

script:
    python3 test_anime.py \
    coverage run test_anime.py

after_success:
    coverage report -m
